// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PUC_Final_Project.Data;

#nullable disable

namespace PUC_Final_Project.Migrations
{
    [DbContext(typeof(BrasileiraoContext))]
    [Migration("20220726210432_PartidaEvento")]
    partial class PartidaEvento
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("PUC_Final_Project.Models.Evento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("Acrescimo")
                        .HasColumnType("int");

                    b.Property<int?>("Advertencia")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Fim")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Gol")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Inicio")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Intervalo")
                        .HasColumnType("int");

                    b.Property<int>("PartidaId")
                        .HasColumnType("int");

                    b.Property<int?>("Substituicao")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PartidaId");

                    b.ToTable("Evento");
                });

            modelBuilder.Entity("PUC_Final_Project.Models.Jogador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pais")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TimeDonoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TimeDonoId");

                    b.ToTable("Jogador");
                });

            modelBuilder.Entity("PUC_Final_Project.Models.Partida", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("TimeCasaId")
                        .HasColumnType("int");

                    b.Property<int>("TimeVisitanteId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TimeCasaId");

                    b.HasIndex("TimeVisitanteId");

                    b.ToTable("Partida");
                });

            modelBuilder.Entity("PUC_Final_Project.Models.Time", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Localidade")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Time");
                });

            modelBuilder.Entity("PUC_Final_Project.Models.Torneio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("PartidaJogadaId")
                        .HasColumnType("int");

                    b.Property<int>("TimeParticipanteId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PartidaJogadaId");

                    b.HasIndex("TimeParticipanteId");

                    b.ToTable("Torneio");
                });

            modelBuilder.Entity("PUC_Final_Project.Models.Transferencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<int>("JogadorTransferidoId")
                        .HasColumnType("int");

                    b.Property<int>("TimeDestinoId")
                        .HasColumnType("int");

                    b.Property<int>("TimeOrigemId")
                        .HasColumnType("int");

                    b.Property<int>("Valor")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("JogadorTransferidoId");

                    b.HasIndex("TimeDestinoId");

                    b.HasIndex("TimeOrigemId");

                    b.ToTable("Transferencia");
                });

            modelBuilder.Entity("PUC_Final_Project.Models.Evento", b =>
                {
                    b.HasOne("PUC_Final_Project.Models.Partida", "Partida")
                        .WithMany("EventoOcorrido")
                        .HasForeignKey("PartidaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Partida");
                });

            modelBuilder.Entity("PUC_Final_Project.Models.Jogador", b =>
                {
                    b.HasOne("PUC_Final_Project.Models.Time", "TimeDono")
                        .WithMany()
                        .HasForeignKey("TimeDonoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TimeDono");
                });

            modelBuilder.Entity("PUC_Final_Project.Models.Partida", b =>
                {
                    b.HasOne("PUC_Final_Project.Models.Time", "TimeCasa")
                        .WithMany()
                        .HasForeignKey("TimeCasaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PUC_Final_Project.Models.Time", "TimeVisitante")
                        .WithMany()
                        .HasForeignKey("TimeVisitanteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TimeCasa");

                    b.Navigation("TimeVisitante");
                });

            modelBuilder.Entity("PUC_Final_Project.Models.Torneio", b =>
                {
                    b.HasOne("PUC_Final_Project.Models.Partida", "PartidaJogada")
                        .WithMany()
                        .HasForeignKey("PartidaJogadaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PUC_Final_Project.Models.Time", "TimeParticipante")
                        .WithMany()
                        .HasForeignKey("TimeParticipanteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PartidaJogada");

                    b.Navigation("TimeParticipante");
                });

            modelBuilder.Entity("PUC_Final_Project.Models.Transferencia", b =>
                {
                    b.HasOne("PUC_Final_Project.Models.Jogador", "JogadorTransferido")
                        .WithMany()
                        .HasForeignKey("JogadorTransferidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PUC_Final_Project.Models.Time", "TimeDestino")
                        .WithMany()
                        .HasForeignKey("TimeDestinoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PUC_Final_Project.Models.Time", "TimeOrigem")
                        .WithMany()
                        .HasForeignKey("TimeOrigemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JogadorTransferido");

                    b.Navigation("TimeDestino");

                    b.Navigation("TimeOrigem");
                });

            modelBuilder.Entity("PUC_Final_Project.Models.Partida", b =>
                {
                    b.Navigation("EventoOcorrido");
                });
#pragma warning restore 612, 618
        }
    }
}
